const STORAGE_KEY='jj_onboarding_plan_v1';
const state={step:0,answers:{}};
const $=id=>document.getElementById(id);
const views=['intro','question-view','result-view'];
const questions=[
 {id:'roleType',title:'What kind of role is this?',help:'Shapes what actually needs covering in week one.',options:[['trade','Trade, construction or field-based work'],['retail','Retail, café or hospitality'],['office','Office, admin or professional role'],['support','Customer service or support'],['driver','Driver, delivery or logistics'],['other','Something else']]},
 {id:'experienceLevel',title:'How experienced is the new starter?',help:'Changes how much you can assume they already know.',options:[['firstjob','This is their first job'],['newindustry','Some experience, but new to this industry'],['experienced','Experienced in this exact type of role'],['rehire','Returning or a rehire']]},
 {id:'teamSize',title:'How big is the team they’re joining?',help:'A two-person team and a structured office need different onboarding.',options:[['solo','Just the two of you'],['small','Small team of 2–5'],['growing','Growing team of 6–20'],['large','Larger, more structured workplace']]},
 {id:'startReason',title:'What’s driving this hire?',help:'Changes the tone and what needs handing over.',options:[['replacing','Replacing someone who left'],['growth','A brand new role due to growth'],['seasonal','Seasonal or temporary'],['casual','Casual pickup work']]},
 {id:'workLocation',title:'Where will they mainly work?',help:'Changes how you handle systems access and check-ins.',options:[['onsite','Always on-site or in person'],['hybrid','A mix of on-site and remote'],['remote','Fully remote'],['mobile','Mobile or on the road']]},
 {id:'systemsAccess',title:'How much system or tool access do they need on day one?',help:'Be realistic—this is often the thing that gets left too late.',options:[['minimal','Minimal—just show up and go'],['few','A few logins—email, roster, basic tools'],['several','Several systems and software'],['unsure','Honestly not sure yet']]},
 {id:'confidence',title:'How confident do you feel onboarding someone properly?',help:'No judgement—this controls how much structure you get.',options:[['comfortable','Comfortable—I just need a checklist'],['unsure','Slightly unsure'],['nervous','Pretty nervous'],['first','This is genuinely my first time']]},
 {id:'notes',title:'Anything specific about this hire?',help:'Optional. Add context, must-dos or things you don’t want to forget.',type:'text'}
];
const visibleQuestions=()=>questions.filter(q=>!q.show||q.show(state));
const scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:scrollBehavior})}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.step=saved.step||0;state.answers=saved.answers||{};return true}}catch{}return false}
function adviceFor(q){
 if(q.id==='systemsAccess'&&state.answers.systemsAccess==='unsure')return `<aside class="advice-card"><h2>Work this out before day one, not during it.</h2><p>Nothing kills a new starter's confidence faster than sitting around on day one waiting for someone to set up a login. Even a rough list beats finding out on the spot.</p></aside>`;
 if(q.id==='confidence'&&['nervous','first'].includes(state.answers.confidence))return `<aside class="advice-card"><h2>A checklist beats a memory.</h2><p>You don't need to hold all of this in your head. A written plan means it happens the same way whether you're flat out or not.</p></aside>`;
 return '';
}
function label(id,value){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===value)?.[1]||value||''}
function renderQuestion(){const list=visibleQuestions();state.step=Math.max(0,Math.min(state.step,list.length-1));const q=list[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${list.length}`;$('progress-bar').style.width=`${((state.step+1)/list.length)*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your plan';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=adviceFor(q);$('back-button').disabled=state.step===0;
 const answers=$('answer-list');answers.innerHTML='';if(q.type==='text'){const area=document.createElement('textarea');area.className='text-answer';area.placeholder='Add anything useful here…';area.value=state.answers[q.id]||'';area.addEventListener('input',()=>{state.answers[q.id]=area.value;save()});answers.append(area)}else q.options.forEach(([value,lbl])=>{const btn=document.createElement('button');btn.type='button';btn.className='answer'+(state.answers[q.id]===value?' selected':'');btn.textContent=lbl;btn.addEventListener('click',()=>{state.answers[q.id]=value;save();renderQuestion()});answers.append(btn)});showView('question-view')}
function beforeDayOne(){const items=['Confirm paperwork—contract, tax file declaration, super and bank details.','Sort access: email, rostering, and any core systems.','Prepare their workspace, tools, uniform or PPE.','Assign a go-to person for their first week—it doesn\'t have to be you.'];if(state.answers.systemsAccess==='several')items.splice(2,0,'Set up all system logins in advance—test them yourself before day one.');return items}
function dayOne(){const map={trade:'Site induction and safety walk-through before anything else.',retail:'POS or till walkthrough, plus a live shift alongside someone experienced.',office:'Desk, systems login, and an intro round of the team.',support:'System walkthrough and listening in on a few real calls or chats.',driver:'Route familiarisation and vehicle/equipment check.',other:'A proper walkthrough of the actual day-to-day tools and space.'};return [map[state.answers.roleType]||map.other,'Introduce them to the team—not just names, but who does what.','Explain what a normal day/week actually looks like.','Set clear, small, achievable tasks for day one—don\'t just observe.']}
function weekOne(){return ['Shadow an experienced person for the first few tasks.','Give them one real, low-risk task to complete independently.','Check in properly at the end of week one—not just a passing "how\'s it going?"','Confirm they know who to ask when they\'re stuck.']}
function plan30(){if(state.answers.experienceLevel==='experienced')return 'Comfortable doing core tasks independently, asking good questions rather than guessing.';return 'Comfortable with the basics, still checking in regularly, starting to work with less supervision.'}
function plan60(){return 'Handling most of the role independently. First proper feedback conversation—what\'s going well, what needs work.'}
function plan90(){if(state.answers.startReason==='casual')return 'Settled into a predictable rhythm, reliable for the shifts they\'re rostered.';return 'Fully across the role. Good time for a proper review conversation and to set goals for the next quarter.'}
function renderResult(){const summary=[label('roleType',state.answers.roleType),label('experienceLevel',state.answers.experienceLevel),label('startReason',state.answers.startReason)].join(' · ');$('result-summary').textContent=summary;$('opening-text').textContent=beforeDayOne().join(' · ');
 const sections=[
  ['Day one',`<ul>${dayOne().map(x=>`<li>${x}</li>`).join('')}</ul>${state.answers.notes?`<p style="margin-top:10px;font-size:.86rem;">Your note: ${escapeHtml(state.answers.notes)}</p>`:''}`,true],
  ['Week one',`<ul>${weekOne().map(x=>`<li>${x}</li>`).join('')}</ul>`,true],
  ['30/60/90-day plan',`<div class="agenda-row"><strong>30 days</strong><span>${plan30()}</span></div><div class="agenda-row"><strong>60 days</strong><span>${plan60()}</span></div><div class="agenda-row"><strong>90 days</strong><span>${plan90()}</span></div>`]
 ];
 $('result-sections').innerHTML=sections.map(([title,body,open])=>`<details ${open?'open':''}><summary>${title}</summary><div class="section-body">${body}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('onboarding_plan',{role_type:state.answers.roleType});showView('result-view');save()}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function next(){const list=visibleQuestions(),q=list[state.step];if(q.type!=='text'&&!state.answers[q.id]){toast('Choose an answer to continue');return}if(state.step>=list.length-1){renderResult();return}state.step++;save();renderQuestion()}
function back(){if(state.step>0){state.step--;save();renderQuestion()}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function planText(){return `NEW STARTER ONBOARDING PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nBEFORE DAY ONE\n${beforeDayOne().map(x=>`- ${x}`).join('\n')}\n\nDAY ONE\n${dayOne().map(x=>`- ${x}`).join('\n')}\n\nWEEK ONE\n${weekOne().map(x=>`- ${x}`).join('\n')}\n\n30/60/90-DAY PLAN\n30 days — ${plan30()}\n60 days — ${plan60()}\n90 days — ${plan90()}\n\nGeneral planning only—not legal, safety or formal HR advice.`}
async function copy(text){await navigator.clipboard.writeText(text);toast('Copied')}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=back;$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>{$('clear-dialog').showModal()};$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden');toast('Saved answers cleared')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});
if(load())$('resume-guide').classList.remove('hidden');
