const STORAGE_KEY='jj_hiring_prep_v1';
const state={step:0,answers:{}};
const $=id=>document.getElementById(id);
const views=['intro','question-view','stop-view','result-view'];
const questions=[
 {id:'roleType',title:'What kind of role are you hiring for?',help:'This shapes the question set and what actually matters day to day.',options:[['trade','Trade, construction or field-based work'],['retail','Retail, café or hospitality'],['office','Office, admin or professional role'],['support','Customer service or support'],['driver','Driver, delivery or logistics'],['care','Community, care or support work'],['other','Something else']]},
 {id:'situation',title:'Is there anything already complicated about this hire?',help:'This changes whether a question set is the right tool right now.',options:[['straightforward','No—this is a straightforward new hire'],['complaint','A candidate I didn’t proceed with has complained, threatened action or raised discrimination'],['dispute','This role involves an unresolved workplace dispute or grievance'],['personal-factors','I’m leaning toward a decision partly based on someone’s age, family situation, pregnancy or similar'],['other-serious','Something else about this feels legally risky']]},
 {id:'employmentType',title:'What’s the employment type?',help:'Casual and full-time hires need slightly different questions.',options:[['fulltime','Full-time'],['parttime','Part-time'],['casual','Casual'],['contractor','Contractor, or I’m not sure yet']]},
 {id:'experienceLevel',title:'What experience level are you after?',help:'Be honest—an entry-level hire and a specialist need very different interviews.',options:[['entry','Entry-level—happy to train'],['some','Some relevant experience'],['specialist','Experienced specialist'],['leadership','A leadership or supervisory hire']]},
 {id:'mainPriority',title:'What matters most for this role?',help:'Pick the thing that actually determines success in the job.',options:[['reliability','Reliability—turning up, on time, every time'],['technical','Technical skill or trade competence'],['customer','How they deal with customers'],['fit','Fitting the existing team'],['learning','Ability to learn quickly'],['other','Something else']]},
 {id:'teamSize',title:'How big is the team they’re joining?',help:'Changes how much structure the interview needs.',options:[['first','This is my first hire'],['small','Small team of 2–5'],['growing','Growing team of 6–20'],['large','Larger, more structured workplace']]},
 {id:'interviewFormat',title:'How do you plan to run it?',help:'Choose the format—this changes the pacing.',options:[['phonefirst','Phone screen first, then in-person'],['inperson','Straight to in-person'],['video','Video call'],['trial','On-site trial or working interview']]},
 {id:'confidence',title:'How confident do you feel running an interview?',help:'No judgement—this controls how much structure you get.',options:[['comfortable','Comfortable—I just need a good question set'],['unsure','Slightly unsure'],['nervous','Pretty nervous'],['first','This is genuinely my first time']]},
 {id:'sensitiveRole',title:'Does this role involve vulnerable people or safety-critical work?',help:'For example: children, elderly or disability care, driving, or operating heavy machinery.',options:[['yes','Yes'],['no','No'],['unsure','Not sure']]},
 {id:'notes',title:'Anything specific about this role?',help:'Optional. Add must-haves, deal-breakers or context you don’t want to forget.',type:'text'}
];
const visibleQuestions=()=>questions.filter(q=>!q.show||q.show(state));
const scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:scrollBehavior})}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.step=saved.step||0;state.answers=saved.answers||{};return true}}catch{}return false}
function adviceFor(q){
 if(q.id==='sensitiveRole')return `<aside class="advice-card"><h2>Checks come before the offer, not after.</h2><p>If this role involves children, vulnerable people or driving, a Working With Children Check, police check or licence verification is normally required before you make an offer—not something to sort out later. Confirm the current requirement for your state.</p></aside>`;
 if(q.id==='confidence'&&['nervous','first'].includes(state.answers.confidence))return `<aside class="advice-card"><h2>You don’t need to wing it.</h2><p>A written question set and a simple scoring approach make you look more prepared than most small businesses hiring for the first time—and it’s fairer to candidates too.</p></aside>`;
 return '';
}
function renderQuestion(){const list=visibleQuestions();state.step=Math.max(0,Math.min(state.step,list.length-1));const q=list[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${list.length}`;$('progress-bar').style.width=`${((state.step+1)/list.length)*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your pack';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=adviceFor(q);$('back-button').disabled=state.step===0;
 const answers=$('answer-list');answers.innerHTML='';if(q.type==='text'){const area=document.createElement('textarea');area.className='text-answer';area.placeholder='Add anything useful here…';area.value=state.answers[q.id]||'';area.addEventListener('input',()=>{state.answers[q.id]=area.value;save()});answers.append(area)}else q.options.forEach(([value,label])=>{const btn=document.createElement('button');btn.type='button';btn.className='answer'+(state.answers[q.id]===value?' selected':'');btn.textContent=label;btn.addEventListener('click',()=>{state.answers[q.id]=value;save();renderQuestion()});answers.append(btn)});showView('question-view')}
function serious(){return ['complaint','dispute','personal-factors','other-serious'].includes(state.answers.situation)}
function label(id,value){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===value)?.[1]||value||''}
function offLimitsList(){return ['Age or date of birth','Marital or family status, or plans to have children','Pregnancy','Religion or political opinion','Race, national origin or ethnicity','Disability, unless directly relevant to safely performing the role','Sexual orientation or gender identity','Union membership'];}
function coreQuestions(){const base=['Tell me about a time something went wrong at work. What did you do?','What does a good day at work look like for you?','Why did you apply for this specific role?'];
 const priorityMap={
  reliability:['Tell me about your attendance record in your last role. Any patterns I should know about?','What would make you late or need to take a day off, realistically?'],
  technical:['Walk me through how you’d approach [a core task in this role].','What’s a mistake you’ve made in this kind of work, and what did you learn from it?'],
  customer:['Tell me about a time you dealt with a difficult customer. How did you handle it?','How do you stay patient when someone’s having a bad day and taking it out on you?'],
  fit:['What kind of team environment do you work best in?','Tell me about a workplace that didn’t suit you. What made it hard?'],
  learning:['Tell me about something you had to learn quickly for a job. How did you approach it?','What do you do when you don’t know how to do something you’ve been asked to do?'],
  other:['What matters most to you in a role like this one?']
 };
 return base.concat(priorityMap[state.answers.mainPriority]||priorityMap.other);
}
function roleFlavour(){const map={trade:'Ask about tools, licences/tickets they hold, and a real scenario from a job site.',retail:'Ask how they’d handle a rush period and a customer complaint at the same time.',office:'Ask about how they prioritise competing deadlines.',support:'Ask them to talk through resolving a customer issue end to end.',driver:'Confirm licence class, driving history comfort level, and ask about a time a delivery/run went wrong.',care:'Ask about a time they supported someone in a vulnerable situation, and how they stayed within their role.',other:'Tailor one question directly to the actual day-to-day of this role.'};return map[state.answers.roleType]||map.other}
function structure(){const format=state.answers.interviewFormat;if(format==='phonefirst')return [['10–15 min','Phone screen—confirm availability, pay expectations and basic fit before you invest more time.'],['30–45 min','In-person or video interview using the full question set.'],['Optional','Working trial or practical task if the role suits it.']];if(format==='trial')return [['20–30 min','Short conversation covering the core questions.'],['1–2 hrs','Paid working trial on a real (low-risk) task.'],['15 min','Debrief—what worked, what didn’t, would you hire them?']];if(format==='video')return [['5 min','Settle them in—video interviews feel more awkward, acknowledge that.'],['30–35 min','Full question set.'],['10 min','Their questions for you, and next steps.']];return [['5 min','Welcome, explain the role and structure of the interview.'],['30–35 min','Full question set.'],['10 min','Their questions for you, and clear next steps.']]}
function afterInterview(){const items=['Take notes during or immediately after—memory fades fast once you’ve seen a few candidates.','Use the same core questions for every candidate so you can fairly compare answers.','Check at least one reference before making an offer.'];if(state.answers.sensitiveRole==='yes')items.unshift('Confirm the required check (Working With Children Check, police check, or licence verification) is complete before the offer is finalised—not after.');items.push('Let unsuccessful candidates know within a reasonable timeframe. A short, courteous message is enough.');return items}
function renderResult(){const summary=[label('roleType',state.answers.roleType),label('employmentType',state.answers.employmentType),label('experienceLevel',state.answers.experienceLevel)].join(' · ');$('result-summary').textContent=summary;$('opening-text').textContent=offLimitsList().join(' · ');
 const sections=[
  ['Before the interview',`<ul><li>Write down what this role actually needs to do, day to day—not just a title.</li><li>${roleFlavour()}</li><li>Decide who’s in the room, and keep it consistent across candidates.</li>${state.answers.notes?`<li>Your note: ${escapeHtml(state.answers.notes)}</li>`:''}</ul>`,true],
  ['Suggested interview questions',`<ul>${coreQuestions().map(x=>`<li>${x}</li>`).join('')}</ul>`,true],
  ['Suggested structure',structure().map(([t,x])=>`<div class="agenda-row"><strong>${t}</strong><span>${x}</span></div>`).join('')],
  ['After the interview',`<ul>${afterInterview().map(x=>`<li>${x}</li>`).join('')}</ul>`]
 ];
 $('result-sections').innerHTML=sections.map(([title,body,open])=>`<details ${open?'open':''}><summary>${title}</summary><div class="section-body">${body}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('hiring_interview_prep',{role_type:state.answers.roleType});showView('result-view');save()}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function next(){const list=visibleQuestions(),q=list[state.step];if(q.type!=='text'&&!state.answers[q.id]){toast('Choose an answer to continue');return}if(q.id==='situation'&&serious()){showView('stop-view');return}if(state.step>=list.length-1){renderResult();return}state.step++;save();renderQuestion()}
function back(){if(state.step>0){state.step--;save();renderQuestion()}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function planText(){return `HIRING & INTERVIEW PREP PACK\n\nSUMMARY\n${$('result-summary').textContent}\n\nLEGALLY OFF-LIMITS\n${offLimitsList().map(x=>`- ${x}`).join('\n')}\n\nBEFORE THE INTERVIEW\n- Write down what this role actually needs to do, day to day.\n- ${roleFlavour()}\n- Decide who's in the room, and keep it consistent across candidates.\n\nSUGGESTED QUESTIONS\n${coreQuestions().map(x=>`- ${x}`).join('\n')}\n\nSTRUCTURE\n${structure().map(x=>`${x[0]} — ${x[1]}`).join('\n')}\n\nAFTER THE INTERVIEW\n${afterInterview().map(x=>`- ${x}`).join('\n')}\n\nGeneral preparation only—not legal or employment advice.`}
async function copy(text){await navigator.clipboard.writeText(text);toast('Copied')}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=back;$('stop-back').onclick=()=>{state.step=Math.max(0,state.step);renderQuestion()};$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>{$('clear-dialog').showModal()};$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden');toast('Saved answers cleared')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});
if(load())$('resume-guide').classList.remove('hidden');
