const STORAGE_KEY='jj_constructive_feedback_v1';
const state={step:0,answers:{}};
const $=id=>document.getElementById(id);
const views=['intro','question-view','stop-view','result-view'];
const questions=[
 {id:'workplace',title:'What kind of workplace is this?',help:'Useful feedback should sound natural in the workplace—not copied from an HR textbook.',options:[['office','Office or professional environment'],['trade','Trade, construction or field-based work'],['mobile','Cleaning, maintenance or mobile services'],['hospitality','Retail, café or hospitality'],['operations','Warehouse, logistics or operations'],['care','Community, care or customer service'],['other','Something else']]},
 {id:'teamSize',title:'How big is the operation?',help:'A two-person business needs clarity, but not a six-page feedback process.',options:[['two','Just me and one other person'],['small','Small team of 2–5'],['growing','Growing team of 6–20'],['large','Larger or more structured workplace']]},
 {id:'person',title:'Who is the feedback for?',help:'Choose the closest fit.',options:[['new','New team member'],['experienced','Experienced team member'],['leader','Supervisor or team leader'],['casual','Casual or part-time employee'],['apprentice','Apprentice or trainee'],['peer','A colleague or peer'],['manager','My manager'],['other','Someone else']]},
 {id:'purpose',title:'What kind of feedback do you need to give?',help:'This separates useful everyday feedback from formal or serious workplace matters.',options:[['positive','Recognise and reinforce good work'],['expectation','Clarify an expectation'],['quality','Improve quality or consistency'],['communication','Improve communication'],['reliability','Address reliability or follow-through'],['customer','Improve a customer or service outcome'],['teamwork','Improve teamwork or behaviour'],['development','Support learning or development'],['performance','Formal or ongoing performance management'],['misconduct','Misconduct or a formal warning'],['termination','Possible termination'],['discrimination','Discrimination, harassment or a complaint'],['safety','A workplace health or safety matter'],['other-serious','Another serious workplace matter']]},
 {id:'example',title:'What specific example are you responding to?',help:'Describe what happened—not what you think it says about their personality.',type:'text',placeholder:'For example: During Friday’s handover, the customer notes were complete and the next person could pick up the job without chasing information.'},
 {id:'impact',title:'What was the main impact?',help:'Feedback lands better when people understand why the example matters.',options:[['customer','Customer or service outcome'],['team','Teamwork or another person’s work'],['time','Time, workload or rework'],['quality','Quality or consistency'],['trust','Trust or communication'],['safety-normal','A normal safe-work reminder—not an incident'],['development','Their confidence or development']]},
 {id:'pattern',title:'Is this a one-off or a pattern?',help:'A single example and a repeated pattern should not be described the same way.',options:[['first','A single or first example'],['sometimes','It has happened a few times'],['pattern','It is becoming a clear pattern'],['improving','It has improved recently'],['consistent','They consistently do this well']]},
 {id:'previous',title:'Have you given them feedback about this before?',help:'Be honest about what you actually said—not what you hoped they understood.',options:[['no','No, not clearly'],['brief','Briefly or in passing'],['yes','Yes, clearly'],['several','Yes, more than once'],['positive-regular','Yes—I regularly recognise this good work']]},
 {id:'outcome',title:'What should happen after the feedback?',help:'Choose one useful outcome instead of trying to fix everything at once.',options:[['repeat','Keep doing the good work'],['understand','Understand why it matters'],['change','Make one specific change'],['practice','Practise or learn a better approach'],['support','Identify support or clearer instructions'],['ownership','Take more ownership'],['checkin','Agree on a check-in or follow-up']]},
 {id:'style',title:'How do they usually receive feedback?',help:'Adjust the delivery, but do not water down the message until it means nothing.',options:[['direct','They prefer it direct'],['friendly','Friendly and conversational works best'],['quiet','They need time to think'],['detailed','They like examples and detail'],['defensive','They may become defensive'],['unknown','I’m honestly not sure']]},
 {id:'confidence',title:'How comfortable are you giving it?',help:'The final plan will give you more structure if you need it.',options:[['comfortable','Comfortable—I need clean wording'],['unsure','A bit unsure'],['nervous','Pretty nervous'],['avoiding','I have been putting it off'],['lost','I have no idea what to say']]},
 {id:'format',title:'How will you give the feedback?',help:'Use the lightest approach that still gives the conversation enough privacy and attention.',options:[['moment','In the moment'],['private','Short private conversation'],['checkin','During a normal check-in'],['phone','Phone or video call'],['written','Written message followed by a conversation'],['unknown','I haven’t decided']]},
 {id:'notes',title:'Anything else you do not want to forget?',help:'Optional. Add context, wording or support you may need to offer.',type:'text',placeholder:'Add useful context here…'}
];
const seriousPurposes=['performance','misconduct','termination','discrimination','safety','other-serious'];
const scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:scrollBehavior})}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.step=saved.step||0;state.answers=saved.answers||{};return true}}catch{}return false}
function adviceFor(q){if(q.id==='example')return '<aside class="advice-card"><h2>Describe it. Do not diagnose them.</h2><p>“The checklist was missed twice this week” is useful. “You’re careless” is a label and gives them nothing practical to work with.</p></aside>';if(q.id==='previous'&&state.answers.pattern==='pattern')return '<aside class="advice-card"><h2>Do not call it a pattern without examples.</h2><p>Bring two or three recent, relevant examples. A giant historical list will feel like an ambush.</p></aside>';if(q.id==='confidence'&&state.answers.purpose==='positive')return '<aside class="advice-card"><h2>Positive feedback should still be specific.</h2><p>“Good job” is pleasant but forgettable. Tell them what they did and why it helped so they know what to repeat.</p></aside>';return ''}
function renderQuestion(){const q=questions[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${questions.length}`;$('progress-bar').style.width=`${((state.step+1)/questions.length)*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your feedback';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=adviceFor(q);$('back-button').disabled=state.step===0;const answers=$('answer-list');answers.innerHTML='';if(q.type==='text'){const area=document.createElement('textarea');area.className='text-answer';area.placeholder=q.placeholder||'Add anything useful here…';area.value=state.answers[q.id]||'';area.addEventListener('input',()=>{state.answers[q.id]=area.value;save()});answers.append(area)}else q.options.forEach(([value,label])=>{const btn=document.createElement('button');btn.type='button';btn.className='answer'+(state.answers[q.id]===value?' selected':'');btn.textContent=label;btn.addEventListener('click',()=>{state.answers[q.id]=value;save();renderQuestion()});answers.append(btn)});showView('question-view')}
function label(id,value){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===value)?.[1]||value||''}
const isPositive=()=>state.answers.purpose==='positive';
function tone(){if(state.answers.style==='direct')return 'Get to the point calmly and use one clear example.';if(state.answers.style==='quiet')return 'Give the feedback, then allow time to think. Do not rush to fill the silence.';if(state.answers.style==='detailed')return 'Use a specific example, explain the impact and be precise about what should continue or change.';if(state.answers.style==='defensive')return 'Keep it factual and steady. Ask for their view without turning the message into an argument.';return 'Keep it natural, specific and two-way.'}
function formatAdvice(){if(state.answers.format==='moment')return 'Keep it short and make sure it is not embarrassing or sensitive in front of other people.';if(state.answers.format==='written')return 'Use the message to introduce the feedback, not to avoid the conversation. Follow up directly.';if(state.answers.format==='phone')return 'Check they have privacy and a few uninterrupted minutes before starting.';if(state.answers.format==='unknown')return 'Use a short private conversation unless the feedback is simple, positive and appropriate to give in the moment.';return 'Choose a private, calm moment with enough time for them to respond.'}
function impactText(){const map={customer:'the customer or service outcome',team:'the team and other people’s work',time:'time, workload or avoidable rework',quality:'the quality and consistency of the work',trust:'trust and communication','safety-normal':'the normal safe way of working',development:'their confidence and development'};return map[state.answers.impact]||'the work'}
function opening(){const example=(state.answers.example||'what happened').trim();if(isPositive())return `I wanted to give you some specific feedback. ${example} That made a real difference to ${impactText()}. Please keep doing that—it’s useful and it doesn’t go unnoticed.`;if(state.answers.previous==='several'||state.answers.pattern==='pattern')return `I want to give you some clear feedback about something we’ve discussed before. ${example} It is affecting ${impactText()}, so I want to hear your view and agree on what needs to change from here.`;return `I want to give you some feedback about a specific example. ${example} It affected ${impactText()}. I’d like to hear your view, then agree on a practical next step.`}
function questionsToAsk(){if(isPositive())return ['What helped you approach it that way?','Is there anything that would make it easier to keep doing this consistently?','Is there another area where you would like to build on this?'];const list=['How did you see the situation?','Was anything unclear or getting in the way?'];if(state.answers.outcome==='practice'||state.answers.outcome==='support')list.push('What support, instruction or practice would actually help?');if(state.answers.previous==='several')list.push('What has made the previously agreed change difficult to maintain?');list.push('What is one specific thing you can do differently next time?','When should we check in on this again?');return list}
function nextStep(){if(isPositive())return 'Name the behaviour you want repeated, make sure they know why it mattered and look for another genuine opportunity to recognise it.';if(state.answers.outcome==='practice')return 'Agree on what they will practise, who can demonstrate it and when you will check progress.';if(state.answers.outcome==='support')return 'Agree on the support or clearer instruction required, without taking ownership of the whole task away from them.';if(state.answers.outcome==='ownership')return 'Ask them to describe the action they will take and how they will keep you informed.';return 'Agree on one observable change, a reasonable timeframe and a short follow-up.'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderResult(){const summary=[label('workplace',state.answers.workplace),label('person',state.answers.person),label('purpose',state.answers.purpose)].join(' · ');$('result-summary').textContent=summary;$('opening-text').textContent=opening();const example=state.answers.example?escapeHtml(state.answers.example):'Add one specific example before giving the feedback.';const sections=[['Before you give it',`<ul><li>${formatAdvice()}</li><li>${tone()}</li><li>Use the example that matters most. Do not unload every old frustration.</li><li>Know what you want them to repeat, understand or change.</li></ul>`,true],['The feedback structure',`<ol><li><strong>Example:</strong> ${example}</li><li><strong>Impact:</strong> Explain how it affected ${impactText()}.</li><li><strong>Next step:</strong> ${nextStep()}</li></ol>`,true],['Questions worth asking',`<ul>${questionsToAsk().map(x=>`<li>${x}</li>`).join('')}</ul>`],['Finish clearly',`<ul><li>${isPositive()?'Thank them without watering it down with an unrelated criticism.':'Confirm the specific action you have both understood.'}</li><li>Check that the expectation is clear.</li><li>${isPositive()?'Keep noticing useful work—not only mistakes.':'Agree when you will follow up.'}</li><li>Write down any action you personally agreed to take.</li></ul>`],['Avoid this nonsense',`<ul><li>Do not use a fake compliment to hide the real message.</li><li>Do not attack their personality or guess their motives.</li><li>Do not compare them with another team member.</li><li>Do not wait six months and then dump everything at once.</li><li>Do not say “everyone thinks” when you are the person giving the feedback.</li></ul>`]];$('result-sections').innerHTML=sections.map(([title,body,open])=>`<details ${open?'open':''}><summary>${title}</summary><div class="section-body">${body}</div></details>`).join('');showView('result-view');save()}
function next(){const q=questions[state.step];if(q.type!=='text'&&!state.answers[q.id]){toast('Choose an answer to continue');return}if(q.id==='purpose'&&seriousPurposes.includes(state.answers.purpose)){showView('stop-view');return}if(state.step>=questions.length-1){renderResult();return}state.step++;save();renderQuestion()}
function back(){if(state.step>0){state.step--;save();renderQuestion()}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function planText(){return `YOUR CONSTRUCTIVE FEEDBACK PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nSUGGESTED WORDING\n${opening()}\n\nSPECIFIC EXAMPLE\n${state.answers.example||'Add one specific example.'}\n\nIMPACT\nExplain how it affected ${impactText()}.\n\nDELIVERY\n- ${formatAdvice()}\n- ${tone()}\n\nQUESTIONS\n${questionsToAsk().map(x=>`- ${x}`).join('\n')}\n\nNEXT STEP\n${nextStep()}\n\nGeneral preparation only—not legal, HR or Fair Work advice.`}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied')}catch{toast('Copy is not available in this browser')}}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=back;$('stop-back').onclick=()=>renderQuestion();$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>$('clear-dialog').showModal();$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden');toast('Saved answers cleared')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});
if(load())$('resume-guide').classList.remove('hidden');
