const STORAGE_KEY='jj_one_on_one_v1';
const state={step:0,answers:{}};
const $=id=>document.getElementById(id);
const views=['intro','question-view','stop-view','result-view'];
const questions=[
 {id:'workplace',title:'What kind of workplace are we talking about?',help:'This changes the tone, structure and where the conversation should happen.',options:[['office','Office or professional environment'],['trade','Trade, construction or field-based work'],['mobile','Cleaning, maintenance or mobile services'],['hospitality','Retail, café or hospitality'],['operations','Warehouse, logistics or operations'],['care','Community, care or customer service'],['other','Something else']]},
 {id:'teamSize',title:'How big is the operation?',help:'A two-person business does not need the same process as a structured office.',options:[['two','Just me and one other person'],['small','Small team of 2–5'],['growing','Growing team of 6–20'],['large','Larger or more structured workplace']]},
 {id:'person',title:'Who is the conversation with?',help:'Choose the option that best describes them.',options:[['new','New team member'],['experienced','Experienced team member'],['leader','Supervisor or team leader'],['casual','Casual or part-time employee'],['apprentice','Apprentice or trainee'],['remote','Remote worker'],['disconnect','Someone I’m struggling to connect with'],['other','Something else']]},
 {id:'style',title:'How do they prefer to communicate?',help:'This helps shape the language and amount of detail.',options:[['direct','Direct—just get to the point'],['friendly','Friendly and conversational'],['quiet','Quiet and needs time to think'],['detailed','Detailed and likes examples'],['defensive','Easily defensive or uncomfortable'],['unknown','I’m honestly not sure']]},
 {id:'history',title:'Is this a normal thing for your team?',help:'Be honest. The advice changes if one-on-ones are new.',options:[['regular','Yes, we do them regularly'],['few','We’ve done a few'],['first','This is our first proper one'],['problems','We normally only talk when something goes wrong']]},
 {id:'frequency',title:'How often do you check in properly?',help:'This includes a useful check-in—not just a quick hello.',options:[['weekly','Every week'],['fortnightly','Every fortnight'],['monthly','Monthly'],['fewmonths','Every few months'],['events','Only when something happens'],['never','Honestly, I don’t']]},
 {id:'confidence',title:'How do you feel about running it?',help:'No judgement. This controls how much structure the final plan gives you.',options:[['comfortable','Comfortable—I just need a good structure'],['unsure','Slightly unsure'],['nervous','Pretty nervous'],['lost','I have absolutely no idea what I’m doing']]},
 {id:'purpose',title:'What does this one-on-one need to achieve?',help:'Choose the main purpose. You can add notes later.',options:[['checkin','General check-in'],['workload','Discuss workload or priorities'],['development','Support development'],['newstarter','Check in with a new starter'],['communication','Improve communication'],['recognition','Recognise good work'],['concern','Address a concern'],['reconnect','Reconnect after a difficult period']]},
 {id:'seriousness',title:'How serious is the issue?',help:'A normal check-in and a formal employment matter need very different handling.',show:s=>['concern','reconnect'].includes(s.answers.purpose),options:[['normal','Normal check-in or small issue'],['minor','Minor concern or pattern'],['performance','Ongoing formal performance concern'],['misconduct','Misconduct or formal warning'],['termination','Possible termination'],['discrimination','Discrimination, harassment or complaint'],['safety','Workplace safety matter'],['other-serious','Another serious workplace matter']]},
 {id:'format',title:'How should this conversation feel?',help:'The guide will adjust the agenda, opening and note-taking.',options:[['casual','Very casual—just a proper check-in'],['relaxed','Relaxed with a few talking points'],['structured','Structured with an agenda'],['formal','Formal because the topic requires it'],['unknown','I’m not sure']]},
 {id:'location',title:'Where will the conversation happen?',help:'Choose somewhere private enough for the topic and practical for the workplace.',options:[['room','Private meeting room'],['quiet','Quiet office or work area'],['field','On-site or in the field'],['cafe','Café or informal location'],['phone','Phone'],['video','Video call'],['unknown','I haven’t worked that out']]},
 {id:'duration',title:'How much time do you have?',help:'The final agenda will fit the time available.',options:[['15','15 minutes'],['30','30 minutes'],['45','45 minutes'],['60','60 minutes']]},
 {id:'notes',title:'Anything specific you need to cover?',help:'Optional. Add wins, workload, challenges, priorities or anything you do not want to forget.',type:'text'}
];
const visibleQuestions=()=>questions.filter(q=>!q.show||q.show(state));
const scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:scrollBehavior})}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.step=saved.step||0;state.answers=saved.answers||{};return true}}catch{}return false}
function adviceFor(q){if(q.id==='frequency'&&['problems'].includes(state.answers.history))return `<aside class="advice-card"><h2>Time to change that.</h2><p>If every proper conversation starts with a problem, people will assume they’re in trouble whenever you ask to speak with them. Start checking in when things are going well too. It doesn’t need to be formal. It just needs to happen.</p></aside>`;if(q.id==='confidence'&&['events','never'].includes(state.answers.frequency))return `<aside class="advice-card"><h2>Regular doesn’t mean corporate.</h2><p>A quick check-in and a proper one-on-one both matter. You need space for the stuff that won’t come up while everyone is flat out.</p></aside>`;return ''}
function renderQuestion(){const list=visibleQuestions();state.step=Math.max(0,Math.min(state.step,list.length-1));const q=list[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${list.length}`;$('progress-bar').style.width=`${((state.step+1)/list.length)*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your plan';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=adviceFor(q);$('back-button').disabled=state.step===0;
 const answers=$('answer-list');answers.innerHTML='';if(q.type==='text'){const area=document.createElement('textarea');area.className='text-answer';area.placeholder='Add anything useful here…';area.value=state.answers[q.id]||'';area.addEventListener('input',()=>{state.answers[q.id]=area.value;save()});answers.append(area)}else q.options.forEach(([value,label])=>{const btn=document.createElement('button');btn.type='button';btn.className='answer'+(state.answers[q.id]===value?' selected':'');btn.textContent=label;btn.addEventListener('click',()=>{state.answers[q.id]=value;save();renderQuestion()});answers.append(btn)});showView('question-view')}
function serious(){return ['performance','misconduct','termination','discrimination','safety','other-serious'].includes(state.answers.seriousness)||state.answers.format==='formal'}
function label(id,value){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===value)?.[1]||value||''}
function tone(){if(state.answers.style==='direct')return 'Keep it direct and explain the purpose without a long build-up.';if(state.answers.style==='quiet')return 'Give them time to think. Ask one question at a time and do not rush to fill every silence.';if(state.answers.style==='detailed')return 'Use specific examples and be clear about what happens next.';if(state.answers.style==='defensive')return 'Keep the tone calm, stick to observable facts and ask for their view before jumping to a conclusion.';return 'Keep it human, clear and genuinely two-way.'}
function opening(){const work=state.answers.workplace;if(['first','problems'].includes(state.answers.history))return `Nothing dramatic—I want us to start checking in properly, not only talking when something has gone wrong. I’d like to hear how work is going from your side and make sure there isn’t anything getting in the way.`;if(work==='trade'||work==='mobile')return `Nothing dramatic—I just want to check in properly, see how work is going from your side and make sure there isn’t anything getting in the way.`;return `I’d like to use this time to check in on your priorities, workload and development, and make sure you have the support you need.`}
function cadence(){if(state.answers.person==='new')return 'Use a short weekly check-in for the first four to six weeks, then reduce it as they become more confident.';if(state.answers.person==='remote')return 'Book a proper fortnightly check-in. Remote work makes it harder to rely on natural workplace conversations.';if(['events','never','fewmonths'].includes(state.answers.frequency))return 'Try a short fortnightly check-in, with a more structured conversation monthly while this becomes normal.';if(state.answers.teamSize==='growing')return 'A short fortnightly check-in usually suits a growing team, supported by normal informal conversations.';return 'Keep normal informal check-ins going and protect a proper conversation at least monthly.'}
function agenda(){const mins=Number(state.answers.duration||30);if(mins===15)return [['2 min','Set the purpose'],['4 min','Ask how work is going'],['5 min','Cover the main topic'],['3 min','Agree actions'],['1 min','Confirm follow-up']];if(mins===45)return [['5 min','Set the purpose and recognise progress'],['10 min','Listen to their view'],['15 min','Discuss workload, blockers and the main topic'],['10 min','Development and support'],['5 min','Agree actions and follow-up']];if(mins===60)return [['5 min','Set the purpose'],['15 min','Their update and workload'],['20 min','Main topic and examples'],['10 min','Development and support'],['10 min','Actions and follow-up']];return [['3 min','Set the purpose'],['7 min','Ask how work is going'],['10 min','Discuss the main topic'],['5 min','Support and development'],['5 min','Agree actions and follow-up']]}
function questionsToAsk(){const base=['What’s working well at the moment?','What’s making the job harder than it needs to be?','Is anything unclear or slowing you down?','What do you need from me?'];if(state.answers.purpose==='development')base.push('What would you like to learn or take on next?');if(state.answers.purpose==='workload')base.push('What feels most urgent, and what can realistically wait?');if(state.answers.purpose==='communication')base.push('What could we do differently to keep each other better informed?');base.push('What should I be doing differently as your manager?');return base}
function renderResult(){const summary=[label('workplace',state.answers.workplace),label('person',state.answers.person),label('format',state.answers.format),`${state.answers.duration||30} minutes`].join(' · ');$('result-summary').textContent=summary;$('opening-text').textContent=opening();const sections=[['Before the conversation',`<ul><li>Choose a private, practical time and place.</li><li>Explain what the conversation is about—no surprises.</li><li>Bring a few notes, not a speech.</li><li>${tone()}</li>${state.answers.notes?`<li>Your note: ${escapeHtml(state.answers.notes)}</li>`:''}</ul>`,true],['Timed agenda',agenda().map(([t,x])=>`<div class="agenda-row"><strong>${t}</strong><span>${x}</span></div>`).join('')],['Questions to ask',`<ul>${questionsToAsk().map(x=>`<li>${x}</li>`).join('')}</ul>`],['Actions and follow-up',`<ul><li>Write down what you agreed to do.</li><li>Confirm what they will do.</li><li>Add realistic due dates.</li><li>Set the next check-in before everyone gets busy again.</li></ul>`],['Suggested check-in rhythm',`<p>${cadence()}</p>`,true]];$('result-sections').innerHTML=sections.map(([title,body,open])=>`<details ${open?'open':''}><summary>${title}</summary><div class="section-body">${body}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('one_on_one',{purpose:state.answers.purpose});showView('result-view');save()}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function next(){const list=visibleQuestions(),q=list[state.step];if(q.type!=='text'&&!state.answers[q.id]){toast('Choose an answer to continue');return}if((q.id==='seriousness'||q.id==='format')&&serious()){showView('stop-view');return}if(state.step>=list.length-1){renderResult();return}state.step++;save();renderQuestion()}
function back(){if(state.step>0){state.step--;save();renderQuestion()}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function planText(){return `YOUR ONE-ON-ONE PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nSUGGESTED OPENING\n${opening()}\n\nBEFORE THE CONVERSATION\n- Choose a private, practical time and place.\n- Explain the purpose—no surprises.\n- Bring a few notes, not a speech.\n- ${tone()}\n\nAGENDA\n${agenda().map(x=>`${x[0]} — ${x[1]}`).join('\n')}\n\nQUESTIONS\n${questionsToAsk().map(x=>`- ${x}`).join('\n')}\n\nCHECK-IN RHYTHM\n${cadence()}\n\nGeneral preparation only—not legal, HR or Fair Work advice.`}
async function copy(text){await navigator.clipboard.writeText(text);toast('Copied')}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=back;$('stop-back').onclick=()=>{state.step=Math.max(0,state.step);renderQuestion()};$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>{$('clear-dialog').showModal()};$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden');toast('Saved answers cleared')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});
if(load())$('resume-guide').classList.remove('hidden');
