const STORAGE_KEY='jj_performance_conv_v1';
const state={step:0,answers:{}};
const $=id=>document.getElementById(id);
const views=['intro','question-view','stop-view','result-view'];
const questions=[
 {id:'workplace',title:'What kind of workplace is this?',help:'Changes the tone and where the conversation should happen.',options:[['trade','Trade, construction or field-based work'],['retail','Retail, café or hospitality'],['office','Office or professional environment'],['support','Customer service or support'],['other','Something else']]},
 {id:'issueType',title:'What’s the performance issue mainly about?',help:'Pick the one that’s the actual core of it.',options:[['quality','Quality or accuracy of the work'],['speed','Missed deadlines or slow output'],['attendance','Attendance or punctuality'],['process','Not following instructions or process'],['attitude','Attitude affecting the rest of the team'],['other','Something else']]},
 {id:'duration',title:'How long has this been going on?',help:'Be honest—this shapes how direct the conversation needs to be.',options:[['new','Just noticed it'],['weeks','A few weeks'],['months','A couple of months'],['long','Much longer than it should have']]},
 {id:'priorConversations',title:'Have you raised this with them before?',help:'This determines whether today is the first chat or a follow-up.',options:[['never','No, never'],['once','Yes, informally, once'],['few','Yes, a few times informally'],['formal','Yes, formally, with notes kept']]},
 {id:'formalStage',title:'Where are you at with this, formally?',help:'Be accurate here—it changes what this guide can safely help with.',options:[['conversation','Just need a proper conversation'],['informal-warning','Given an informal warning already'],['formal-process','Already in a formal warning or performance process'],['termination','Considering ending their employment']]},
 {id:'impact',title:'What’s it actually affecting?',help:'Concrete impact makes the conversation clearer and fairer.',options:[['workload','Other people’s workload'],['customer','Customer experience'],['deadlines','Deadlines or deliverables'],['safety','Safety'],['morale','Team morale']]},
 {id:'awareness',title:'Do they seem aware there’s a problem?',help:'This changes how you open the conversation.',options:[['trying','Yes, and they seem to be trying'],['aware','Yes, but nothing’s changing'],['unaware','No idea it’s an issue'],['defensive','Gets defensive when it’s raised']]},
 {id:'confidence',title:'How confident do you feel having this conversation?',help:'No judgement—this controls how much structure you get.',options:[['comfortable','Comfortable—I just need a structure'],['unsure','Slightly unsure'],['nervous','Pretty nervous'],['first','Genuinely my first time doing this']]},
 {id:'notes',title:'Anything specific you want to cover?',help:'Optional. Add specific examples, dates or context you don’t want to forget.',type:'text'}
];
const visibleQuestions=()=>questions.filter(q=>!q.show||q.show(state));
const scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:scrollBehavior})}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.step=saved.step||0;state.answers=saved.answers||{};return true}}catch{}return false}
function formalEscalation(){return ['formal-process','termination'].includes(state.answers.formalStage)}
function adviceFor(q){
 if(q.id==='priorConversations'&&state.answers.priorConversations==='never')return `<aside class="advice-card"><h2>Start direct, not dramatic.</h2><p>If this is the first time you're raising it, keep the tone matter-of-fact. One clear conversation now is easier than three vague hints later.</p></aside>`;
 if(q.id==='awareness'&&state.answers.awareness==='defensive')return `<aside class="advice-card"><h2>Stick to facts, not character.</h2><p>Talk about specific, observable examples rather than generalisations. "On Tuesday the report was two days late" lands very differently to "you're always late with things."</p></aside>`;
 return '';
}
function label(id,value){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===value)?.[1]||value||''}
function renderQuestion(){const list=visibleQuestions();state.step=Math.max(0,Math.min(state.step,list.length-1));const q=list[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${list.length}`;$('progress-bar').style.width=`${((state.step+1)/list.length)*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your plan';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=adviceFor(q);$('back-button').disabled=state.step===0;
 const answers=$('answer-list');answers.innerHTML='';if(q.type==='text'){const area=document.createElement('textarea');area.className='text-answer';area.placeholder='Add anything useful here…';area.value=state.answers[q.id]||'';area.addEventListener('input',()=>{state.answers[q.id]=area.value;save()});answers.append(area)}else q.options.forEach(([value,lbl])=>{const btn=document.createElement('button');btn.type='button';btn.className='answer'+(state.answers[q.id]===value?' selected':'');btn.textContent=lbl;btn.addEventListener('click',()=>{state.answers[q.id]=value;save();renderQuestion()});answers.append(btn)});showView('question-view')}
function opening(){const issue=label('issueType',state.answers.issueType).toLowerCase();if(state.answers.priorConversations==='never')return `I want to talk to you about ${issue} — I don't think this is something either of us wants to let drift, so I'd rather raise it directly now.`;return `I want to follow up on ${issue}, which we've touched on before. I still want to work through it with you, so let's talk about what's actually getting in the way.`}
function structure(){return [['2 min','Open directly—name the topic, no long preamble.'],['5 min','Describe the specific, observable issue with an example.'],['8 min','Ask their view. Actually listen before responding.'],['5 min','Agree what needs to change and by when.'],['3 min','Confirm the next check-in date.']]}
function documentationTrail(){return ['Date and time of the conversation.','What was specifically discussed—use real examples, not general impressions.','What the person said in response.','What you both agreed needs to change.','A realistic timeframe for improvement.','The date of your next check-in.'];}
function cadence(){if(state.answers.duration==='long')return 'Check in weekly for the next few weeks—this has been going on long enough that a monthly review won\'t catch problems early.';if(state.answers.priorConversations==='few')return 'Check in fortnightly. Multiple informal chats without change usually means the follow-up needs to be more structured.';return 'Check in within two weeks to see whether things have genuinely shifted, then monthly after that.'}
function renderResult(){if(formalEscalation()){showView('stop-view');return}
 const summary=[label('workplace',state.answers.workplace),label('issueType',state.answers.issueType),label('duration',state.answers.duration)].join(' · ');$('result-summary').textContent=summary;$('opening-text').textContent=opening();
 const sections=[
  ['Before the conversation',`<ul><li>Choose a private, practical time and place.</li><li>Write down two or three specific, dated examples—not vague impressions.</li><li>Decide what a realistic, fair timeframe for improvement looks like.</li>${state.answers.notes?`<li>Your note: ${escapeHtml(state.answers.notes)}</li>`:''}</ul>`,true],
  ['Suggested structure',structure().map(([t,x])=>`<div class="agenda-row"><strong>${t}</strong><span>${x}</span></div>`).join(''),true],
  ['What to document afterward',`<ul>${documentationTrail().map(x=>`<li>${x}</li>`).join('')}</ul><p style="margin-top:10px;font-size:.86rem;">Keep this even if the conversation feels informal—a simple written record protects both of you if things need to become formal later.</p>`],
  ['Suggested check-in rhythm',`<p>${cadence()}</p>`]
 ];
 $('result-sections').innerHTML=sections.map(([title,body,open])=>`<details ${open?'open':''}><summary>${title}</summary><div class="section-body">${body}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('performance_conversation',{issue_type:state.answers.issueType});showView('result-view');save()}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function next(){const list=visibleQuestions(),q=list[state.step];if(q.type!=='text'&&!state.answers[q.id]){toast('Choose an answer to continue');return}if(q.id==='formalStage'&&formalEscalation()){showView('stop-view');return}if(state.step>=list.length-1){renderResult();return}state.step++;save();renderQuestion()}
function back(){if(state.step>0){state.step--;save();renderQuestion()}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function planText(){return `PERFORMANCE CONVERSATION PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nSUGGESTED OPENING\n${opening()}\n\nSTRUCTURE\n${structure().map(x=>`${x[0]} — ${x[1]}`).join('\n')}\n\nDOCUMENT AFTERWARD\n${documentationTrail().map(x=>`- ${x}`).join('\n')}\n\nCHECK-IN RHYTHM\n${cadence()}\n\nGeneral preparation only—not legal, HR or Fair Work advice.`}
async function copy(text){await navigator.clipboard.writeText(text);toast('Copied')}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=back;$('stop-back').onclick=()=>{state.step=Math.max(0,state.step);renderQuestion()};$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>{$('clear-dialog').showModal()};$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden');toast('Saved answers cleared')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});
if(load())$('resume-guide').classList.remove('hidden');
