const STORAGE_KEY='jj_difficult_conversation_v1';
const state={step:0,answers:{}};
const $=id=>document.getElementById(id);
const views=['intro','question-view','stop-view','result-view'];
const questions=[
 {id:'workplace',title:'What kind of workplace is this?',help:'The useful level of formality changes depending on where and how the work happens.',options:[['office','Office or professional environment'],['trade','Trade, construction or field-based work'],['mobile','Cleaning, maintenance or mobile services'],['hospitality','Retail, café or hospitality'],['operations','Warehouse, logistics or operations'],['care','Community, care or customer service'],['other','Something else']]},
 {id:'teamSize',title:'How big is the operation?',help:'A conversation in a two-person business feels different from one in a structured workplace.',options:[['two','Just me and one other person'],['small','Small team of 2–5'],['growing','Growing team of 6–20'],['large','Larger or more structured workplace']]},
 {id:'person',title:'Who do you need to speak with?',help:'Choose the closest fit.',options:[['new','New team member'],['experienced','Experienced team member'],['leader','Supervisor or team leader'],['casual','Casual or part-time employee'],['apprentice','Apprentice or trainee'],['peer','A colleague or peer'],['manager','My manager'],['other','Someone else']]},
 {id:'matter',title:'What is the conversation mainly about?',help:'This check keeps normal workplace friction separate from matters that need proper professional advice.',options:[['expectation','A missed expectation or incomplete work'],['reliability','Reliability, lateness or follow-through'],['communication','Communication or attitude'],['quality','Quality of work or customer service'],['boundary','A boundary or behaviour that needs to change'],['tension','Tension or a working relationship problem'],['workload','Workload, priorities or capacity'],['performance','Formal or ongoing performance management'],['misconduct','Misconduct or a formal warning'],['termination','Possible termination'],['discrimination','Discrimination, harassment or a complaint'],['safety','A workplace health or safety matter'],['other-serious','Another serious workplace matter']]},
 {id:'facts',title:'What actually happened?',help:'Stick to what you saw, heard, received or can verify. Leave motives and mind-reading out of it.',type:'text',placeholder:'For example: The customer update was due Tuesday. It was still incomplete on Thursday and nobody had been told about the delay.'},
 {id:'impact',title:'What has the issue affected?',help:'Choose the main impact. This helps explain why the conversation matters.',options:[['customer','A customer or service outcome'],['team','The rest of the team'],['time','Time, workload or rework'],['trust','Trust or communication'],['quality','Quality or consistency'],['person','The person’s own work or development'],['small','It is still small—I want to address it early']]},
 {id:'history',title:'Have you discussed this before?',help:'Do not pretend a repeated issue is the first conversation—or treat a first issue like a final warning.',options:[['first','No, this is the first conversation'],['informal','Briefly or informally'],['clear','Yes, we have discussed it clearly'],['several','Yes, more than once'],['unsure','I’m not sure it was understood']]},
 {id:'outcome',title:'What would a useful outcome look like?',help:'Choose the most practical result for this conversation.',options:[['understand','Understand what happened'],['clarity','Make the expectation clear'],['change','Agree on a specific change'],['support','Work out what support is needed'],['repair','Repair the working relationship'],['plan','Agree on actions and a follow-up'],['listen','Hear their side before deciding anything']]},
 {id:'style',title:'How do they usually communicate?',help:'This adjusts the tone—not the facts.',options:[['direct','Direct—just get to the point'],['friendly','Friendly and conversational'],['quiet','Quiet and needs time to think'],['detailed','Detailed and likes examples'],['defensive','Can become defensive or uncomfortable'],['unknown','I’m honestly not sure']]},
 {id:'confidence',title:'How comfortable are you having the conversation?',help:'No judgement. The final plan will give you more structure if you need it.',options:[['comfortable','Comfortable—I need a clean plan'],['unsure','A bit unsure'],['nervous','Pretty nervous'],['avoiding','I have been avoiding it'],['lost','I have no idea what to say']]},
 {id:'location',title:'Where will you have it?',help:'Private and practical beats dramatic. Do not raise personal issues in front of the team or customers.',options:[['room','Private meeting room'],['quiet','Quiet office or work area'],['site','Private spot on-site'],['phone','Phone'],['video','Video call'],['unknown','I haven’t worked that out']]},
 {id:'duration',title:'How much time can you allow?',help:'Leave enough room for their side of the story.',options:[['15','15 minutes'],['30','30 minutes'],['45','45 minutes'],['60','60 minutes']]},
 {id:'notes',title:'Anything else you do not want to forget?',help:'Optional. Add relevant context, examples or questions—not a list of every annoying thing they have ever done.',type:'text',placeholder:'Add useful context here…'}
];
const seriousMatters=['performance','misconduct','termination','discrimination','safety','other-serious'];
const scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:scrollBehavior})}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.step=saved.step||0;state.answers=saved.answers||{};return true}}catch{}return false}
function adviceFor(q){if(q.id==='facts')return '<aside class="advice-card"><h2>Facts first. Frustration second.</h2><p>“You don’t care” is an assumption. “The last three customer updates were sent after the promised time” is something you can discuss.</p></aside>';if(q.id==='history'&&state.answers.matter==='reliability')return '<aside class="advice-card"><h2>Do not save it all up.</h2><p>Small issues are easier to address early. A calm conversation now is usually better than an explosion after six more examples.</p></aside>';if(q.id==='confidence'&&['several','clear'].includes(state.answers.history))return '<aside class="advice-card"><h2>A repeated issue needs clarity.</h2><p>Be honest that it has been discussed before, explain the current impact and agree on a specific next step. Do not make vague threats.</p></aside>';return ''}
function renderQuestion(){const q=questions[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${questions.length}`;$('progress-bar').style.width=`${((state.step+1)/questions.length)*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your plan';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=adviceFor(q);$('back-button').disabled=state.step===0;const answers=$('answer-list');answers.innerHTML='';if(q.type==='text'){const area=document.createElement('textarea');area.className='text-answer';area.placeholder=q.placeholder||'Add anything useful here…';area.value=state.answers[q.id]||'';area.addEventListener('input',()=>{state.answers[q.id]=area.value;save()});answers.append(area)}else q.options.forEach(([value,label])=>{const btn=document.createElement('button');btn.type='button';btn.className='answer'+(state.answers[q.id]===value?' selected':'');btn.textContent=label;btn.addEventListener('click',()=>{state.answers[q.id]=value;save();renderQuestion()});answers.append(btn)});showView('question-view')}
function label(id,value){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===value)?.[1]||value||''}
function tone(){if(state.answers.style==='direct')return 'Be direct and calm. State the issue without a long, nervous build-up.';if(state.answers.style==='quiet')return 'Ask one question at a time, allow silence and give them time to think before expecting an answer.';if(state.answers.style==='detailed')return 'Use one or two specific examples and clearly explain the expected next step.';if(state.answers.style==='defensive')return 'Keep your voice steady, use observable facts and ask for their view before arguing your conclusion.';return 'Keep it human, specific and two-way.'}
function setting(){if(state.answers.location==='site')return 'Choose a genuinely private spot away from customers and the rest of the crew—not the ute with three people standing nearby.';if(['phone','video'].includes(state.answers.location))return 'Check they are somewhere private and have enough time. Do not spring it on them between jobs.';if(state.answers.location==='unknown')return 'Choose a private, neutral place where neither of you needs to perform for an audience.';return 'Use the private space properly: close the door, remove distractions and allow enough time.'}
function opening(){const topic=label('matter',state.answers.matter).toLowerCase();if(state.answers.history==='first')return `I want to talk about ${topic}. I’ll explain what I’ve noticed, but I also want to understand what’s happening from your side so we can agree on a sensible way forward.`;if(['clear','several'].includes(state.answers.history))return `I want to come back to ${topic}. We’ve discussed it before and I need us to be clear about what’s still happening, the impact it’s having and what needs to change from here. I also want to hear your view.`;return `I want to have a proper conversation about ${topic}. This isn’t about having a go at you—I want to explain the concern, hear your side and agree on what happens next.`}
function impactText(){const map={customer:'the customer or service outcome',team:'the rest of the team',time:'time, workload or avoidable rework',trust:'trust and communication',quality:'the quality or consistency of the work',person:'the person’s work or development',small:'the work—and you are raising it early before it becomes a larger issue'};return map[state.answers.impact]||'the work'}
function questionsToAsk(){const list=['Can you talk me through what happened from your side?','Is there something getting in the way that I may not be seeing?'];if(state.answers.outcome==='support'||state.answers.matter==='workload')list.push('What support, clarity or change would make this more manageable?');if(state.answers.outcome==='repair'||state.answers.matter==='tension')list.push('What needs to change on both sides for the working relationship to improve?');if(['clear','several'].includes(state.answers.history))list.push('What was unclear or difficult about the action we previously agreed?');list.push('What do you think is a realistic next step?','How will we both know this has improved?');return list}
function agenda(){const mins=Number(state.answers.duration||30);if(mins===15)return [['2 min','Explain the purpose'],['4 min','Share the facts and impact'],['5 min','Hear their side'],['3 min','Agree the next step'],['1 min','Confirm follow-up']];if(mins===45)return [['5 min','Set a calm purpose'],['8 min','Explain the facts and impact'],['15 min','Listen and clarify'],['12 min','Agree actions and support'],['5 min','Confirm follow-up']];if(mins===60)return [['5 min','Set the purpose'],['10 min','Explain the facts and impact'],['20 min','Listen and ask questions'],['15 min','Work through options and support'],['10 min','Agree actions and follow-up']];return [['3 min','Set the purpose'],['7 min','Explain the facts and impact'],['10 min','Hear their side'],['7 min','Agree actions and support'],['3 min','Confirm follow-up']]}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderResult(){const summary=[label('workplace',state.answers.workplace),label('person',state.answers.person),label('matter',state.answers.matter),`${state.answers.duration||30} minutes`].join(' · ');$('result-summary').textContent=summary;$('opening-text').textContent=opening();const fact=state.answers.facts?escapeHtml(state.answers.facts):'Add one or two specific, observable examples before the conversation.';const sections=[['Before you start',`<ul><li>${setting()}</li><li>Know the outcome you want, but stay open to information you do not have yet.</li><li>Bring the relevant facts—not a character assessment.</li><li>${tone()}</li></ul>`,true],['Facts and impact',`<p><strong>What happened:</strong> ${fact}</p><p><strong>Why it matters:</strong> Explain the effect on ${impactText()} without exaggerating it.</p>`,true],['Timed conversation structure',agenda().map(([t,x])=>`<div class="agenda-row"><strong>${t}</strong><span>${x}</span></div>`).join('')],['Questions worth asking',`<ul>${questionsToAsk().map(x=>`<li>${x}</li>`).join('')}</ul>`],['Agree the next step',`<ul><li>State clearly what needs to happen next.</li><li>Ask what support or clarity is reasonably needed.</li><li>Agree who will do what and by when.</li><li>Set a follow-up date instead of relying on memory.</li><li>Make a short factual note after the conversation.</li></ul>`],['What not to do',`<ul><li>Do not ambush them in front of other people.</li><li>Do not unload six months of stored frustration.</li><li>Do not use “always” and “never” when one clear example will do.</li><li>Do not promise an outcome before hearing their side.</li><li>Do not bluff about formal consequences.</li></ul>`]];$('result-sections').innerHTML=sections.map(([title,body,open])=>`<details ${open?'open':''}><summary>${title}</summary><div class="section-body">${body}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('difficult_conversation',{matter:state.answers.matter});showView('result-view');save()}
function next(){const q=questions[state.step];if(q.type!=='text'&&!state.answers[q.id]){toast('Choose an answer to continue');return}if(q.id==='matter'&&seriousMatters.includes(state.answers.matter)){showView('stop-view');return}if(state.step>=questions.length-1){renderResult();return}state.step++;save();renderQuestion()}
function back(){if(state.step>0){state.step--;save();renderQuestion()}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function planText(){return `YOUR DIFFICULT CONVERSATION PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nSUGGESTED OPENING\n${opening()}\n\nFACTS\n${state.answers.facts||'Add one or two specific, observable examples.'}\n\nIMPACT\nExplain the effect on ${impactText()}.\n\nBEFORE YOU START\n- ${setting()}\n- ${tone()}\n- Bring facts, not a character assessment.\n\nSTRUCTURE\n${agenda().map(x=>`${x[0]} — ${x[1]}`).join('\n')}\n\nQUESTIONS\n${questionsToAsk().map(x=>`- ${x}`).join('\n')}\n\nNEXT STEPS\n- Agree who will do what and by when.\n- Confirm any support or clarity needed.\n- Set a follow-up date.\n- Keep a short factual note.\n\nGeneral preparation only—not legal, HR or Fair Work advice.`}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied')}catch{toast('Copy is not available in this browser')}}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=back;$('stop-back').onclick=()=>renderQuestion();$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>$('clear-dialog').showModal();$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden');toast('Saved answers cleared')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});
if(load())$('resume-guide').classList.remove('hidden');
