const STORAGE_KEY='jj_career_development_v1',state={step:0,answers:{}},$=id=>document.getElementById(id),views=['intro','question-view','stop-view','result-view'],scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
const questions=[
 {id:'workplace',title:'What kind of workplace are you in?',help:'Development can be structured or very practical. The plan should suit where you work.',options:[['office','Office or professional environment'],['trade','Trade, construction or field-based work'],['mobile','Cleaning, maintenance or mobile services'],['hospitality','Retail, café or hospitality'],['operations','Warehouse, logistics or operations'],['care','Community, care or customer service'],['other','Something else']]},
 {id:'tenure',title:'How long have you been in your current role?',help:'This helps set a realistic starting point.',options:[['new','Less than 6 months'],['year','6–12 months'],['established','1–3 years'],['long','More than 3 years']]},
 {id:'direction',title:'How do you want to develop?',help:'Pick the direction that feels most useful right now.',options:[['current','Get better in my current role'],['responsibility','Take on more responsibility'],['leadership','Build leadership capability'],['technical','Build a technical or specialist skill'],['future-role','Prepare for a future role'],['confidence','Build confidence and communication'],['unclear','I know I want growth but not what kind']]},
 {id:'driver',title:'Why does this matter to you?',help:'A clear reason helps you stay practical when opportunities take time.',options:[['impact','I want to make a bigger contribution'],['challenge','I need more challenge'],['career','I want a clearer career direction'],['skills','I want useful new skills'],['recognition','I want my capability to be recognised'],['stuck','I feel stuck'],['unsure','I am still working that out']]},
 {id:'strengths',title:'What are you already good at?',help:'Use real work examples, not generic claims.',type:'text',placeholder:'For example: customer conversations, training new starters, organising work, solving system problems or maintaining quality.'},
 {id:'skill',title:'What do you most need to build?',help:'One useful focus is better than a giant wish list.',options:[['technical','Technical knowledge'],['leadership','Leading or supporting people'],['communication','Communication or confidence'],['planning','Planning and prioritising'],['commercial','Business or commercial understanding'],['qualification','A qualification or licence'],['unknown','I need help identifying it']]},
 {id:'method',title:'How do you learn best?',help:'Development does not always require an expensive course.',options:[['doing','Doing real work with guidance'],['shadowing','Shadowing someone experienced'],['feedback','Regular feedback and coaching'],['course','A structured course or qualification'],['reading','Self-guided learning'],['mix','A practical mix']]},
 {id:'manager',title:'How is communication with your manager?',help:'This shapes how directly you can raise the conversation.',options:[['regular','We already speak regularly'],['good','Good, but development rarely comes up'],['busy','They are supportive but very busy'],['new','They do not know my work well yet'],['difficult','It can be difficult or inconsistent'],['none','We barely have proper conversations']]},
 {id:'previous',title:'Have you raised development before?',help:'Do not assume a vague comment was understood as a real request.',options:[['no','No, not properly'],['hinted','I have hinted at it'],['once','Yes, once'],['ongoing','Yes, it is an ongoing conversation'],['stalled','Yes, but nothing happened']]},
 {id:'support',title:'What support would be most useful?',help:'Choose something your manager can actually respond to.',options:[['opportunity','A stretch task or new responsibility'],['time','Time to learn or practise'],['mentor','Coaching, mentoring or shadowing'],['feedback','Clearer and more regular feedback'],['training','Training or course support'],['clarity','Help choosing a development direction']]},
 {id:'serious',title:'Is a serious workplace issue driving this?',help:'A development conversation is not the right tool for every problem.',options:[['no','No—this is a normal development conversation'],['discrimination','I believe discrimination or retaliation is involved'],['dispute','There is an active formal workplace dispute'],['performance','I am currently in a formal performance process']]},
 {id:'confidence',title:'How comfortable are you asking?',help:'The final plan will add structure where you need it.',options:[['comfortable','Comfortable—I need a clear plan'],['unsure','A bit unsure'],['nervous','Pretty nervous'],['avoiding','I have been putting it off'],['lost','I do not know what to ask for']]},
 {id:'timeframe',title:'What timeframe feels realistic?',help:'Development works better with a check-in point.',options:[['month','Start within the next month'],['quarter','Build something over three months'],['six','Work towards it over six months'],['year','Longer-term direction over 12 months'],['unknown','I need my manager’s input']]},
 {id:'notes',title:'Anything else you do not want to forget?',help:'Optional. Add a skill, opportunity or question you want to discuss.',type:'text',placeholder:'Add useful context here…'}
];const serious=['discrimination','dispute','performance'];
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));scrollTo({top:0,behavior:scrollBehavior})}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x){state.step=x.step||0;state.answers=x.answers||{};return true}}catch{}return false}
function advice(q){if(q.id==='direction'&&['long'].includes(state.answers.tenure))return '<aside class="advice-card"><h2>Time served is not a development plan.</h2><p>Being there a long time can strengthen your case, but focus on what you want to learn, contribute or take responsibility for next.</p></aside>';if(q.id==='strengths')return '<aside class="advice-card"><h2>Make it easy to understand your value.</h2><p>Pick examples where your work helped a customer, the team, quality, time or a result. “I’m ready” is not evidence by itself.</p></aside>';if(q.id==='support'&&state.answers.previous==='stalled')return '<aside class="advice-card"><h2>Turn the vague promise into an action.</h2><p>Ask for one specific opportunity, owner and timeframe. “We’ll look at it later” is not a development plan.</p></aside>';return ''}
function renderQuestion(){const q=questions[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${questions.length}`;$('progress-bar').style.width=`${(state.step+1)/questions.length*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your plan';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=advice(q);$('back-button').disabled=!state.step;const box=$('answer-list');box.innerHTML='';if(q.type==='text'){const a=document.createElement('textarea');a.className='text-answer';a.placeholder=q.placeholder;a.value=state.answers[q.id]||'';a.oninput=()=>{state.answers[q.id]=a.value;save()};box.append(a)}else q.options.forEach(([v,l])=>{const b=document.createElement('button');b.type='button';b.className='answer'+(state.answers[q.id]===v?' selected':'');b.textContent=l;b.onclick=()=>{state.answers[q.id]=v;save();renderQuestion()};box.append(b)});showView('question-view')}
function label(id,v){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===v)?.[1]||v||''}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function opening(){if(state.answers.direction==='unclear')return `I want to be more deliberate about my development here. I know I want to keep growing, but I’m not yet clear on the best direction. Could we talk about where you see my strengths, what I should build and one practical opportunity I could start with?`;if(state.answers.previous==='stalled')return `I’d like to come back to the development conversation we had. I’m still interested in ${label('direction',state.answers.direction).toLowerCase()}, and I’d like us to turn it into one clear action and a timeframe rather than leave it open-ended.`;return `I’d like to have a proper conversation about my development. I’m interested in ${label('direction',state.answers.direction).toLowerCase()}, and I want to understand what I should build and what practical opportunity could help me start.`}
function skillPlan(){const m={technical:'Choose one specific technical capability and find a real task where you can practise it with review.',leadership:'Take responsibility for a small outcome, handover, training task or improvement before chasing a title.',communication:'Choose one communication behaviour to practise and ask for feedback after relevant situations.',planning:'Own a small plan, priority list or workflow and review what worked with your manager.',commercial:'Ask to understand the customer, cost or business outcome behind a piece of work you already touch.',qualification:'Confirm whether the qualification is genuinely required, then compare realistic providers, time and cost.',unknown:'Ask your manager which capability would make the biggest difference to your work over the next three months.'};return m[state.answers.skill]||m.unknown}
 function renderResult(){const strengths=state.answers.strengths?escapeHtml(state.answers.strengths):'Add two or three real examples of work you do well.';$('result-summary').textContent=[label('workplace',state.answers.workplace),label('direction',state.answers.direction),label('timeframe',state.answers.timeframe)].join(' · ');$('opening-text').textContent=opening();const sections=[['Get clear on the goal',`<ul><li>Your direction: ${label('direction',state.answers.direction)}.</li><li>Your reason: ${label('driver',state.answers.driver)}.</li><li>Describe the kind of work or capability you want—not only a future title.</li></ul>`,true],['What you already bring',`<p>${strengths}</p><p>Prepare two examples and explain what they improved or made easier.</p>`,true],['Your practical development action',`<p>${skillPlan()}</p><p>Preferred learning approach: ${label('method',state.answers.method)}.</p>`,true],['How to ask',`<ul><li>Set aside enough time for a real conversation.</li><li>Use the suggested opening and explain why the development matters.</li><li>Ask what your manager believes the priority gap is.</li><li>Request ${label('support',state.answers.support).toLowerCase()}.</li><li>Agree on one action rather than a giant plan nobody follows.</li></ul>`],['Questions worth asking',`<ul><li>What strength do you think I should build on?</li><li>What capability would make the biggest difference in my role?</li><li>Is there a real task or responsibility where I can practise it?</li><li>What would good progress look like?</li><li>When should we review it?</li></ul>`],['Your development cycle',`<ol><li>Choose one skill.</li><li>Use it in real work.</li><li>Ask for specific feedback.</li><li>Adjust and practise again.</li><li>Review progress ${label('timeframe',state.answers.timeframe).toLowerCase()}.</li></ol>`],['If the answer is no',`<ul><li>Ask whether the issue is timing, budget, opportunity or readiness.</li><li>Ask what you can do without formal funding.</li><li>Agree when the conversation can be revisited.</li><li>Keep ownership of your development while being realistic about what the workplace can provide.</li></ul>`]];$('result-sections').innerHTML=sections.map(([t,b,o])=>`<details ${o?'open':''}><summary>${t}</summary><div class="section-body">${b}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('career_development',{direction:state.answers.direction});showView('result-view');save()}
function next(){const q=questions[state.step];if(q.type!=='text'&&!state.answers[q.id])return toast('Choose an answer to continue');if(q.id==='serious'&&serious.includes(state.answers.serious))return showView('stop-view');if(state.step===questions.length-1)return renderResult();state.step++;save();renderQuestion()}function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}async function copy(t){try{await navigator.clipboard.writeText(t);toast('Copied')}catch{toast('Copy is not available')}}
function planText(){return `YOUR CAREER DEVELOPMENT PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nSUGGESTED OPENING\n${opening()}\n\nWHAT I ALREADY BRING\n${state.answers.strengths||'Add two or three real examples.'}\n\nSKILL TO BUILD\n${label('skill',state.answers.skill)}\n${skillPlan()}\n\nSUPPORT TO ASK FOR\n${label('support',state.answers.support)}\n\nNEXT STEP\nChoose one action and one review date.\n\nGeneral preparation only—not legal, HR or Fair Work advice.`}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=()=>{if(state.step){state.step--;save();renderQuestion()}};$('stop-back').onclick=renderQuestion;$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>$('clear-dialog').showModal();$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});if(load())$('resume-guide').classList.remove('hidden');
