const STORAGE_KEY='jj_internal_role_v1',state={step:0,answers:{}},$=id=>document.getElementById(id),views=['intro','question-view','stop-view','result-view'],scrollBehavior=window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
const questions=[
 {id:'workplace',title:'What kind of workplace are you in?',help:'This changes how formal and structured the approach should be.',options:[['office','Office or professional environment'],['trade','Trade, construction or field-based work'],['mobile','Cleaning, maintenance or mobile services'],['hospitality','Retail, café or hospitality'],['operations','Warehouse, logistics or operations'],['care','Community, care or customer service'],['other','Something else']]},
 {id:'tenure',title:'How long have you been there?',help:'Time served is not everything, but it changes the evidence you can use.',options:[['new','Less than 6 months'],['year','6–12 months'],['established','1–3 years'],['long','More than 3 years']]},
 {id:'move',title:'What kind of move are you considering?',help:'Pick the closest option. You do not need the perfect job title yet.',options:[['promotion','A promotion into leadership'],['same-team','A different role in the same team'],['department','A move to another department'],['responsibility','More responsibility in my current role'],['unclear','I’m interested but not sure what fits']]},
 {id:'status',title:'How real is the opportunity?',help:'Your approach should match what actually exists.',options:[['open','There is an advertised internal role'],['upcoming','A role may open soon'],['idea','I want to propose a possible move'],['explore','I only want to explore options'],['rejected','I previously expressed interest and was not selected']]},
 {id:'reason',title:'Why do you want the move?',help:'Choose the reason you can explain honestly and constructively.',options:[['growth','I am ready to grow'],['skills','The work suits my skills better'],['impact','I could contribute more there'],['change','I need a new challenge'],['leadership','I want to lead or support others'],['escape','I mainly want to get away from my current role'],['unsure','I am still working that out']]},
 {id:'strengths',title:'What can you already bring?',help:'Use real skills, experience or results—not “I work hard”.',type:'text',placeholder:'For example: I already train new starters, understand the customer workflow and have improved our handover checklist.'},
 {id:'evidence',title:'What evidence supports you?',help:'Choose the strongest type of proof you can discuss.',options:[['results','Clear results or improvements'],['experience','Relevant experience or responsibilities'],['feedback','Positive feedback from others'],['acting','I have already acted in similar duties'],['learning','Training or qualifications'],['little','I need to build stronger evidence']]},
 {id:'gap',title:'What is the biggest gap?',help:'Being realistic about a gap makes you sound prepared, not weak.',options:[['technical','Technical knowledge or qualification'],['leadership','Leadership experience'],['experience','Direct experience in that area'],['confidence','Confidence or interview skills'],['visibility','The right people do not know my work'],['unknown','I do not know yet'],['none','I appear to meet the main requirements']]},
 {id:'relationship',title:'How is your relationship with your manager?',help:'This shapes who to speak with and how direct you can be.',options:[['strong','Open and supportive'],['normal','Generally fine'],['new-manager','They are new or do not know my work well'],['difficult','A bit difficult or inconsistent'],['other-manager','The opportunity sits with another manager']]},
 {id:'serious',title:'Is a serious workplace issue affecting this?',help:'A career plan should not disguise something that needs proper advice.',options:[['no','No—this is a normal career move'],['performance','I am currently in a formal performance process'],['redundancy','Redundancy or redeployment may be involved'],['discrimination','I believe discrimination or retaliation is involved'],['dispute','There is an active formal workplace dispute']]},
 {id:'confidence',title:'How comfortable are you raising it?',help:'The final plan will give you more structure if needed.',options:[['comfortable','Comfortable—I need a clean approach'],['unsure','A bit unsure'],['nervous','Pretty nervous'],['avoiding','I have been avoiding it'],['lost','I do not know where to begin']]},
 {id:'timing',title:'When do you want to raise it?',help:'Give yourself enough preparation time without waiting forever.',options:[['week','Within the next week'],['month','Within the next month'],['review','At my next review or one-on-one'],['opening','When the role opens'],['unknown','I have not decided']]},
 {id:'notes',title:'Anything else you do not want to forget?',help:'Optional. Add the role, team, person to speak with or useful context.',type:'text',placeholder:'Add useful context here…'}
];
const serious=['performance','redundancy','discrimination','dispute'];
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));scrollTo({top:0,behavior:scrollBehavior})}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saved-label')?.classList.remove('hidden')}function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x){state.step=x.step||0;state.answers=x.answers||{};return true}}catch{}return false}
function advice(q){if(q.id==='reason'&&state.answers.move==='unclear')return '<aside class="advice-card"><h2>You do not need the title first.</h2><p>Start with the kind of work, responsibility or problem you want more of. That gives your manager something useful to explore with you.</p></aside>';if(q.id==='strengths')return '<aside class="advice-card"><h2>Evidence beats enthusiasm.</h2><p>Interest matters, but examples make the conversation real. Think about work you already do, improvements you made and responsibilities people trust you with.</p></aside>';if(q.id==='relationship'&&state.answers.reason==='escape')return '<aside class="advice-card"><h2>Do not lead with what you hate.</h2><p>It is fine to want change. Explain what you want to move towards and the value you can bring—not only what you want to escape.</p></aside>';return ''}
function renderQuestion(){const q=questions[state.step];$('progress-label').textContent=`Question ${state.step+1} of ${questions.length}`;$('progress-bar').style.width=`${(state.step+1)/questions.length*100}%`;$('question-kicker').textContent=q.id==='notes'?'Last step':'Build your plan';$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('context-advice').innerHTML=advice(q);$('back-button').disabled=!state.step;const box=$('answer-list');box.innerHTML='';if(q.type==='text'){const a=document.createElement('textarea');a.className='text-answer';a.placeholder=q.placeholder;a.value=state.answers[q.id]||'';a.oninput=()=>{state.answers[q.id]=a.value;save()};box.append(a)}else q.options.forEach(([v,l])=>{const b=document.createElement('button');b.type='button';b.className='answer'+(state.answers[q.id]===v?' selected':'');b.textContent=l;b.onclick=()=>{state.answers[q.id]=v;save();renderQuestion()};box.append(b)});showView('question-view')}
function label(id,v){const q=questions.find(x=>x.id===id);return q?.options?.find(x=>x[0]===v)?.[1]||v||''}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function opening(){if(state.answers.move==='unclear')return `I’ve been thinking about how I could grow here and contribute more. I’m not locked onto a job title yet, but I’d like to explore the kind of work or responsibility that could be a good next step. Could we talk through where you think my strengths may fit?`;if(state.answers.status==='open')return `I’m interested in the internal opportunity and I’d like to have a proper conversation before I apply. I think my current experience gives me a useful foundation, and I’d value your honest view on my fit and anything I should address.`;return `I’ve been enjoying the work I’m doing and I’m keen to take on more impact. I’m interested in exploring ${label('move',state.answers.move).toLowerCase()} and wanted your honest view on what I already bring, what I still need to build and how I could work towards it.`}
function gapPlan(){const m={technical:'Find the exact knowledge or qualification required and agree on one practical way to start building it.',leadership:'Take responsibility for a small piece of work, handover, training or team support that demonstrates leadership without pretending to be the boss.',experience:'Ask for exposure, shadowing or a small stretch task connected to the target work.',confidence:'Prepare two examples of useful work and practise explaining them without underselling yourself.',visibility:'Share relevant outcomes and ask for work that makes your capability visible to the right people.',unknown:'Ask the manager what the two biggest gaps are and request specific examples.',none:'Validate that view with the role requirements and ask for honest feedback before assuming you are ready.'};return m[state.answers.gap]||m.unknown}
function renderResult(){const strengths=state.answers.strengths?escapeHtml(state.answers.strengths):'Add two or three specific examples of work, results or responsibility.';$('result-summary').textContent=[label('workplace',state.answers.workplace),label('move',state.answers.move),label('status',state.answers.status)].join(' · ');$('opening-text').textContent=opening();const sections=[['Get clear before you ask',`<ul><li>Explain the kind of work or responsibility you want more of.</li><li>Connect the move to contribution and growth—not only a new title.</li><li>Read the role requirements or find out what the work actually involves.</li></ul>`,true],['What you already bring',`<p>${strengths}</p><p>Choose your best two examples and explain the result or difference they made.</p>`,true],['Gaps to work on',`<p>${gapPlan()}</p>`],['How to raise it',`<ul><li>Ask for a proper conversation rather than dropping hints.</li><li>Use the suggested opening, then pause and listen.</li><li>Ask: “What would you need to see from me to seriously consider me?”</li><li>Ask for a concrete opportunity to build or demonstrate the missing experience.</li><li>Do not demand a promise or immediate promotion.</li></ul>`],['Your next 30 days',`<ol><li>Write down the target work and why it suits you.</li><li>Collect two useful examples of what you already bring.</li><li>Have the conversation by ${label('timing',state.answers.timing).toLowerCase()}.</li><li>Agree on one development action and one follow-up date.</li><li>Keep delivering in your current role while you work towards the next one.</li></ol>`],['If the answer is not yet',`<ul><li>Ask what specifically is missing.</li><li>Ask what evidence would change the decision.</li><li>Agree on a realistic review point.</li><li>Decide whether the opportunity and timeframe still work for you.</li></ul>`]];$('result-sections').innerHTML=sections.map(([t,b,o])=>`<details ${o?'open':''}><summary>${t}</summary><div class="section-body">${b}</div></details>`).join('');window.trackToolCompletion&&window.trackToolCompletion('internal_role',{move_type:state.answers.move});showView('result-view');save()}
function next(){const q=questions[state.step];if(q.type!=='text'&&!state.answers[q.id])return toast('Choose an answer to continue');if(q.id==='serious'&&serious.includes(state.answers.serious))return showView('stop-view');if(state.step===questions.length-1)return renderResult();state.step++;save();renderQuestion()}function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}async function copy(t){try{await navigator.clipboard.writeText(t);toast('Copied')}catch{toast('Copy is not available')}}
function planText(){return `YOUR INTERNAL MOVE PLAN\n\nSUMMARY\n${$('result-summary').textContent}\n\nSUGGESTED OPENING\n${opening()}\n\nWHAT I BRING\n${state.answers.strengths||'Add two or three specific examples.'}\n\nGAP TO WORK ON\n${gapPlan()}\n\nNEXT 30 DAYS\n- Collect two examples.\n- Have the conversation.\n- Agree one development action.\n- Set a follow-up date.\n\nGeneral preparation only—not legal, HR or Fair Work advice.`}
$('start-guide').onclick=()=>{state.step=0;state.answers={};save();renderQuestion()};$('resume-guide').onclick=renderQuestion;$('continue-button').onclick=next;$('back-button').onclick=()=>{if(state.step){state.step--;save();renderQuestion()}};$('stop-back').onclick=renderQuestion;$('edit-answers').onclick=renderQuestion;$('copy-plan').onclick=()=>copy(planText());$('restart-guide').onclick=()=>$('clear-dialog').showModal();$('save-exit').onclick=()=>{save();location.href='../'};$('confirm-clear').onclick=()=>{localStorage.removeItem(STORAGE_KEY);state.step=0;state.answers={};$('clear-dialog').close();showView('intro');$('resume-guide').classList.add('hidden')};$('cancel-clear').onclick=()=>$('clear-dialog').close();document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copy($(b.dataset.copy).textContent)});if(load())$('resume-guide').classList.remove('hidden');
